import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'
import path from 'path'
import { fileURLToPath } from 'url'
import { readFileSync } from 'fs'

// Get __dirname equivalent for ES modules
const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Helper function to load canister IDs from canister_ids.json
function loadCanisterIds(projectRoot: string, network: string = 'local'): Record<string, string> {
  try {
    const canisterIdsPath = path.join(projectRoot, '.dfx', network, 'canister_ids.json')
    const canisterIdsContent = readFileSync(canisterIdsPath, 'utf-8')
    const canisterIds = JSON.parse(canisterIdsContent)
    
    // Convert to flat structure with CANISTER_ID_* format
    // Handle both "local" and "ic" networks
    const result: Record<string, string> = {}
    for (const [canisterName, canisterData] of Object.entries(canisterIds)) {
      if (typeof canisterData === 'object' && canisterData !== null) {
        // Check if this network exists in the canister data
        if (network in canisterData) {
          // Convert canister name to CANISTER_ID_* format
          // e.g., "arbitra_backend" -> "CANISTER_ID_ARBITRA_BACKEND"
          const normalizedName = canisterName.toUpperCase().replace(/-/g, '_')
          const key = `CANISTER_ID_${normalizedName}`
          result[key] = (canisterData as any)[network]
        }
      }
    }
    console.log(`Loaded canister IDs from .dfx/${network}/canister_ids.json:`, Object.keys(result))
    return result
  } catch (error) {
    console.warn(`Could not load canister_ids.json from .dfx/${network}/canister_ids.json:`, error)
    return {}
  }
}

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  // Load env file from project root (where .env is generated by dfx)
  // vite.config.ts is in src/arbitra_frontend, so go up two levels to project root
  // Path: src/arbitra_frontend -> src -> project root
  const projectRoot = path.resolve(__dirname, '../..')
  const env = loadEnv(mode, projectRoot, '')
  
  // Determine network (local or ic)
  const network = env.DFX_NETWORK || env.VITE_DFX_NETWORK || 'local'
  
  // Load canister IDs from canister_ids.json as fallback
  const canisterIdsFromFile = loadCanisterIds(projectRoot, network)
  
  // Merge: env vars take precedence, then canister_ids.json, then empty string
  const getCanisterId = (canisterName: string): string => {
    const viteKey = `VITE_${canisterName}_CANISTER_ID`
    const canisterKey = `CANISTER_ID_${canisterName}`
    return env[viteKey] || env[canisterKey] || canisterIdsFromFile[canisterKey] || ''
  }
  
  return {
    plugins: [react()],
    // Explicitly set the environment directory to project root
    envDir: projectRoot,
    build: {
      outDir: 'dist',
      emptyOutDir: true,
    },
    server: {
      proxy: {
        '/api': {
          target: 'http://localhost:4943',
          changeOrigin: true,
        },
      },
    },
    // Expose environment variables to the client
    envPrefix: 'VITE_',
    // Define environment variables for build time replacement
    // These will replace import.meta.env.VITE_* in the code at build time
    define: {
      'import.meta.env.VITE_DFX_NETWORK': JSON.stringify(network),
      'import.meta.env.VITE_ARBITRA_BACKEND_CANISTER_ID': JSON.stringify(getCanisterId('ARBITRA_BACKEND')),
      'import.meta.env.VITE_EVIDENCE_MANAGER_CANISTER_ID': JSON.stringify(getCanisterId('EVIDENCE_MANAGER')),
      'import.meta.env.VITE_AI_ANALYSIS_CANISTER_ID': JSON.stringify(getCanisterId('AI_ANALYSIS')),
      'import.meta.env.VITE_BITCOIN_ESCROW_CANISTER_ID': JSON.stringify(getCanisterId('BITCOIN_ESCROW')),
      'import.meta.env.VITE_INTERNET_IDENTITY_CANISTER_ID': JSON.stringify(
        env.VITE_INTERNET_IDENTITY_CANISTER_ID || 
        env.CANISTER_ID_INTERNET_IDENTITY || 
        canisterIdsFromFile.CANISTER_ID_INTERNET_IDENTITY ||
        (network === 'ic' ? 'rdmx6-jaaaa-aaaaa-aaadq-cai' : 'ufxgi-4p777-77774-qaadq-cai')
      ),
      'import.meta.env.VITE_ARBITRA_FRONTEND_CANISTER_ID': JSON.stringify(
        env.VITE_ARBITRA_FRONTEND_CANISTER_ID || 
        env.CANISTER_ID_ARBITRA_FRONTEND || 
        canisterIdsFromFile.CANISTER_ID_ARBITRA_FRONTEND ||
        ''
      ),
    },
  }
})
